### ISSUE TITLE
It isn't working on .jsx ('javascriptreact')

### ISSUE THREAD

**Issue by luigiMinardi** [antiantisepticeye/vscode-color-picker#6]
settings.json
![settings](https://user-images.githubusercontent.com/53359163/159126664-0e42b6c4-3283-41d9-95f4-2b3a99f4336b.png)
any.jsx
![jsx](https://user-images.githubusercontent.com/53359163/159126656-b31cfa48-3bf7-467b-997e-f7296521da68.png)
any.js
![js](https://user-images.githubusercontent.com/53359163/159126657-104f393e-371d-42e1-8f4f-878331777532.png)

Tried with `.tsx` and also didn't worked (`.ts` works fine though).

**Comment by Energiz3r** [comment]
Works for me - just needed to disable / enable the plugin and off it went.

**Comment by MrKennDmsi** [comment]
Doesn't work for me either, in any type of file.

**Comment by 0xalecks** [comment]
same.. doesn't work in settings.json, despite `jsonc` being in the list

**Comment by lrgcrypto** [comment]
By default the VSCode will enable color picker for stylesheet files such as .css, .less, .scss and .sass

In order to have the color picker for other file types, wherever there is an valid HEX tag, also to make the valid answer more complete, there are two steps to follow,

install extension [vscode-color-picker](https://marketplace.visualstudio.com/items?itemName=AntiAntiSepticeye.vscode-color-picker).

add following to the seetings.json of your VSCode, since by default it enables for [python,javascript,typescript]

"vscode-color-picker.languages": [
"php",
"html",
"css",
"python",
"jsonc",
"javascript",
"javascriptreact",
"typescript",
"typescriptreact",
"vue"
]

**Comment by flatcapped** [comment]
> In order to have the color picker for other file types, wherever there is an valid HEX tag, also to make the valid answer more complete, there are two steps to follow

You also need to make sure that "editor.colorDecorators" is not set to "false" in settings.json

**Comment by svetliott** [comment]
Interesting... 

adding only "typescriptreact" didn't work after reload (disable/enable)
after adding javascript react... and again disable/enable it worked ... I hope this helps

working settings : 
 "vscode-color-picker.languages": [
        "typescriptreact",
        "javascriptreact",
        "python",
        "javascript",
        "typescript"
    ],

**Comment by thiagobraga** [comment]
> You also need to make sure that "editor.colorDecorators" is not set to "false" in settings.json

It's true, the extension wasn't working, but after I've changed `editor.colorDecorators` to `true`, it worked.

But I've found some issues:
- only `js` file worked, not `jsx`, `tsx` or `ts` (edit: sometimes neither `js` works)
- `css` worked but after a reload, now it shows two color picker boxes
- in `jsonc`, it also shows twice, one of them inside of the string

![image](https://github.com/antiantisepticeye/vscode-color-picker/assets/993684/d05d2f5b-53e6-4090-b5b3-93380ec5b615)
![image](https://github.com/antiantisepticeye/vscode-color-picker/assets/993684/e0c63c1c-7064-4d7c-bf96-2541f5a7fb17)
![image](https://github.com/antiantisepticeye/vscode-color-picker/assets/993684/b458bd29-8f37-406f-841c-d7c9fb24c3e3)


I saw an error on Extension Host output
```
2023-10-26 17:39:16.216 [error] [AntiAntiSepticeye.vscode-color-picker] provider FAILED
2023-10-26 17:39:16.217 [error] TypeError: Cannot read properties of undefined (reading 'index')
	at s (/home/thiago/.vscode/extensions/antiantisepticeye.vscode-color-picker-0.0.4/dist/extension.js:2:24643)
	at /home/thiago/.vscode/extensions/antiantisepticeye.vscode-color-picker-0.0.4/dist/extension.js:2:25630
	at Array.map (<anonymous>)
	at Function.getMatches (/home/thiago/.vscode/extensions/antiantisepticeye.vscode-color-picker-0.0.4/dist/extension.js:2:25422)
	at Object.provideDocumentColors (/home/thiago/.vscode/extensions/antiantisepticeye.vscode-color-picker-0.0.4/dist/extension.js:2:26110)
	at _.provideColors (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:127:58754)
	at /usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:127:74684
	at be.s (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:127:63736)
	at be.$provideDocumentColors (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:127:74671)
	at i.S (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:134:10827)
	at i.Q (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:134:10593)
	at i.M (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:134:9645)
	at i.L (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:134:8762)
	at s.value (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:134:7565)
	at c.z (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:80:1902)
	at c.fire (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:80:2119)
	at m.fire (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:96:14010)
	at s.value (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:153:7902)
	at c.z (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:80:1902)
	at c.fire (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:80:2119)
	at m.fire (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:96:14010)
	at MessagePortMain.<anonymous> (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:153:6182)
	at MessagePortMain.emit (node:events:513:28)
	at MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:367)
```
